leonardo_kkadavy_orders/urls.py
from django.conf.urls import patterns, url
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    url(r'^objednavaci-list/pridat/$', views.KkadavyOrderCreate.as_view(), name='objedn_list'),
]

leonardo_kkadavy_orders/models.py
# encoding: utf-8
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
import datetime

CHOICES_TYPE_KNEDLIKY = (
 ('HOUSKOVÉ KNEDLÍKY', (
   ('khouskovy800', 'Knedlík houskový - velký 800g'),
   ('khouskovy800kr', 'Knedlík houskový - velký krájený 800g'),
   ('khouskovy600', 'Knedlík houskový - malý 600g'),
   ('khouskovy600kr', 'Knedlík houskový - malý krájený 600g'),
   ('khouskovy300', 'Knedlík houskový - mini 300g'),
   ('kstarocesky', 'Staročeský knedlík - 600g'),
   ('kstaroceskyk', 'Staročeský knedlík - krájený 600g'),
  )
 ),
 ('KYNUTÉ KNEDLÍKY', (
   ('kpb', 'Kynuté knedlíky plněné ovocem - borůvka 350g v bal. 4ks'),
   ('kpb1', 'Kynuté knedlíky plněné ovocem - borůvka v bal. 1ks (1 knedlík)'),
   ('kpj', 'Kynuté knedlíky plněné ovocem - jahoda 350g v bal. 4ks'),
   ('kpj1', 'Kynuté knedlíky plněné ovocem - jahoda v bal. 1ks (1 knedlík)'),
   ('kpm', 'Kynuté knedlíky plněné ovocem - meruňka 350g v bal. 4ks'),
   ('kpm1', 'Kynuté knedlíky plněné ovocem - meruňka v bal. 1ks (1 knedlík)'),
   ('ksnb', 'Kynuté knedlíky s náplní - borůvka 350g v bal. 6ks'),
   ('ksnb1', 'Kynuté knedlíky s náplní - borůvka v bal. 1ks (1 knedlík)'),
   ('ksnj', 'Kynuté knedlíky s náplní - jahoda 350g v bal. 6ks'),
   ('ksnj1', 'Kynuté knedlíky s náplní - jahoda v bal. 1ks (1 knedlík)'),
   ('ksnm', 'Kynuté knedlíky s náplní - meruňka 350g v bal. 6ks'),
   ('ksnm1', 'Kynuté knedlíky s náplní - meruňka v bal. 1ks (1 knedlík)'),
   ('kspnm1', 'Kynuté knedlíky s povidly - 350g v bal. 4ks'),
   ('kspnm', 'Kynuté knedlíky s povidly - v bal. 1ks (1 knedlík)'),
  )
 ),
 ('TVAROHOVÉ KNEDLÍKY', (
   ('tps', 'Tvarohové knedlíky plněné ovocem - švestka 350g v bal. 6ks'),
   ('tps1', 'Tvarohové knedlíky plněné ovocem - švestka v bal. 1ks (1 knedlík)'),
   ('tpj', 'Tvarohové knedlíky plněné ovocem - jahoda 350g v bal. 6ks'),
   ('tpj1', 'Tvarohové knedlíky plněné ovocem - jahoda v bal. 1ks (1 knedlík)'),
   ('tpm', 'Tvarohové knedlíky plněné ovocem - meruňka 350g v bal. 6ks'),
   ('tpm1', 'Tvarohové knedlíky plněné ovocem - meruňka v bal. 1ks (1 knedlík)'),
  )
 ),
 ('BRAMBOROVÉ KNEDLÍKY', (
   ('bpum', 'Bramborové knedlíky plněné uzeným masem - 350g v bal. 6ks'),
   ('bpum1', 'Bramborové knedlíky plněné uzeným masem - v bal. 1ks'),
   ('b2pum', 'Bramborové knedlíky 2x plněné uzeným masem - 350g v bal. 6ks'),
   ('b2pum1', 'Bramborové knedlíky 2x plněné uzeným masem - v bal. 1ks'),
   ('bkss', 'Bramborové knedlíky se švestkami - 500g v bal. 8ks'),
   ('bkss1', 'Bramborové knedlíky se švestkami - v bal. 1ks'),
   ('bpp', 'Bramborové taštičky plněné povidly - 350g v bal. 6ks'),
   ('bpp1', 'Bramborové taštičky plněné povidly - v bal. 1ks'),
   ('ptpt', 'Bramborové taštičky plněné tvarohem - 350g v bal. 6ks'),
   ('ptpt1', 'Bramborové taštičky plněné tvarohem - v bal. 1ks'),
   ('bk', 'Bramborový knedlík - 400g'),
   ('bkk', 'Bramborový knedlík - krájený 400g'),
   ('bs', 'Bramborové špalíčky - 400g'),
   ('bskg', 'Bramborové špalíčky - 1kg'),
   ('bsm', 'Bramborové šišky s mákem - 400g'),
   ('bsmkg', 'Bramborové šišky s mákem - 1kg'),
  )
 ),
 ('OSTATNÍ VÝROBKY', (
   ('chk', 'Chlupaté knedlíky - 400g'),
   ('chkkg', 'Chlupaté knedlíky - 1kg'),
   ('hom', 'Halušky od Marušky - 400g'),
   ('homkg', 'Halušky od Marušky - 1kg'),
   ('bp', 'Babiččiny palačinky - 300g v bal. 3ks'),
   ('bp1', 'Babiččiny palačinky - 1ks'),
   ('b', 'Bramboráky - 400g v bal. 5ks'),
   ('b1', 'Bramboráky - 1ks'),
   ('lt', 'Listové těsto - 500g'),
   ('ltkg', 'Listové těsto - 1kg'),
   ('kkarlovarsky', 'Karlovarský knedlík (při objednávce nad 15ks) - 500g'),
  )
 ),
)


class KkadavyOrders(models.Model):
    jmeno = models.CharField(max_length=255, verbose_name=u"Jméno", default='')
    prijmeni = models.CharField(
        max_length=255, verbose_name=u"Příjmení", default='')
    email = models.EmailField(verbose_name=u"E-mail", default='')
    telefon = models.PositiveIntegerField(verbose_name=u"Telefon", default="")
    adresa = models.CharField(max_length=255, verbose_name=u"Doručovací adresa", default='')
    firma = models.CharField(max_length=255, verbose_name=u"Název firmy", default='', blank=True, help_text="Nepovinné pole")
    ico = models.CharField(max_length=255, verbose_name=u"IČO", default='', blank=True, help_text=u"Nepovinné pole")
    dic = models.CharField(max_length=255, verbose_name=u"DIČ", default='', blank=True, help_text=u"Nepovinné pole")
    pub_date = models.DateTimeField(u'Datum objednávky', auto_now_add=True)
    def __unicode__(self):
        return (self.prijmeni + self.jmeno)
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=2) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = u'Nedávno vytvořené? (2 dny)'

    class Meta:
        ordering = ['prijmeni', ]
        verbose_name = u'Objednávka'
        verbose_name_plural = u'Objednávky'


class KkadavyProducts(models.Model):
    order = models.ForeignKey(KkadavyOrders,verbose_name=u"Objednávka", related_name="orderproduct_set")
    type_of_product = models.CharField(verbose_name=u"Produkt", choices=CHOICES_TYPE_KNEDLIKY, max_length=100)
    quantity = models.PositiveIntegerField(verbose_name=u"Počet")
    def __unicode__(self):
        return self.type_of_product

    class Meta:
        ordering = ['type_of_product', ]
        verbose_name = u'Produkt'
        verbose_name_plural = u'Produkty'

leonardo_kkadavy_orders/widget/kkadavyorders/models.py
# encoding: utf-8

from django.db import models
from django.utils.translation import ugettext_lazy as _
from leonardo.module.web.models import Widget
from leonardo_kkadavy_orders.models import KkadavyOrders, KkadavyProducts
from django.forms import inlineformset_factory


class KkadavyOrdersWidget(Widget):

    def get_items(self):
        return KkadavyOrders.objects.all().order_by("-pub_date")

    class Meta:
        abstract = True
        verbose_name = 'Order kkadavy'
        verbose_name_plural = 'Orders kkadavy'

leonardo_kkadavy_orders/templates/leonardo_kkadavy_orders/_kkadavyorders_form.html
{% extends "leonardo/common/_modal.html" %}
{% load i18n staticfiles crispy_forms_tags %}

{% block form_id %}kkadavy_order_formset{% endblock %}
{% block form_action %}{% url "objedn_list" %}{% endblock %}

{% block modal-body %}
<div class="col-sm-12">
    <br>
    <div class="alert alert-info alert-dismissable fade in">
        <strong>INFO!</strong> Pro nové zákazníky zavezeme objednávku až po telefonické domluvě. (+420 775 920 020)
        <a href="#" class="close-alert" data-dismiss="alert" aria-label="close">&times;</a>
    </div>
    <form action="{% url 'objedn_list' %}" method="post">{% csrf_token %}
        {% crispy form %}
        <div class="col-sm-12">
        <table class="table">
            {{ orderproducts.management_form }}

            {% for form in orderproducts.forms %}
                {% if forloop.first %}
                    <thead>
                    <tr>
                        {% for field in form.visible_fields %}
                            <th>{{ field.label|capfirst }}</th>
                        {% endfor %}
                    </tr>
                    </thead>
                {% endif %}
                <tr class="{% cycle row1 row2 %} formset_row">
                    {% for field in form.visible_fields %}
                        <td>
                            {# Include the hidden fields in the form #}
                            {% if forloop.first %}
                                {% for hidden in form.hidden_fields %}
                                    {{ hidden }}
                                {% endfor %}
                            {% endif %}
                            {{ field.errors.as_ul }}
                            {{ field }}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
        </div>
        <input class="btn btn-submit-order" type="submit" value="{{ submit_label }}"/>
    </form>
</div>
<script src="{% static 'formset/jquery.formset.js' %}"></script>
<script type="text/javascript">
setTimeout(function(){
    $('.formset_row').formset({
        addText: 'Přidat produkt',
        deleteText: '',
        prefix: 'orderproduct_set'
    });
    $("#kkadavy_order_formset th:contains('Delete')").text("Zrušit")
    if ($('.dynamic-form:not([style*="display: none"])').length == 1) {
        $("#kkadavy_order_formset .delete-row").hide();
    }
    $("#kkadavy_order_formset .delete-row").html("<i class='fa fa-times-circle remove-btn-formset' aria-hidden='true'></i>")
    $("#kkadavy_order_formset .add-row").click(function(){
        $("#kkadavy_order_formset .delete-row").html("<i class='fa fa-times-circle remove-btn-formset' aria-hidden='true'></i>")
        $("#kkadavy_order_formset .delete-row").click(function(){
            setTimeout(function(){
                if ($('.dynamic-form:not([style*="display: none"])').length == 1) {
                    $("#kkadavy_order_formset .delete-row").hide();
                }
            }, 10);
        });
    });
}, 100);
</script>
{% endblock %}

{% block modal-footer %}
<style type="text/css">
.modal-footer p {
    color: #fff;
}
.modal-footer a {
    color: #fff;
    text-decoration: underline;
}
.modal-footer a:hover {
    text-decoration: none;
}
</style>
<p>Kliknutím na tlačítko "Potvrdit" dáváte souhlas k odeslání tohoto formuláře se všemi údaji. Více informací naleznete na stránce <a style="font-weight: bold;" href="/informace-o-webu#gdpr-info">Informace o webu</a></p>
<i style="color: #d4d4d4">Pole označená hvězdičkou (<span style="color: #d22019">*</span>) jsou povinná.</i>
{% endblock %}

leonardo_kkadavy_orders/templates/leonardo_kkadavy_orders/kkadavy_email.html
<h2>Objednávka - {{ jmeno }} {{ prijmeni }} - {% now "d.m. Y H:i" %}</h2>

<h3>Jméno: {{ jmeno }} {{ prijmeni }}</h3>
<table style="border: 1px solid #757575;padding: 6px;width: 100%;">
    <tr>
      <th style="text-align: left;padding: 4px">Telefon:</th>
      <td>{{ telefon }}</td>
    </tr>
    <tr>
      <th style="text-align: left;padding: 4px">E-mail:</th>
      <td>{{ email }}</td>
    </tr>
    <tr>
      <th style="text-align: left;padding: 4px">Doručovací adresa:</th>
      <td>{{ adresa }}</td>
    </tr>
    <tr>
      <th style="text-align: left;padding: 4px">Firma:</th>
      <td>{% if firma %}{{ firma }}{% else %}neuvedeno{% endif %}</td>
    </tr>
    <tr>
      <th style="text-align: left;padding: 4px">IČO:</th>
      <td>{% if ico %}{{ ico }}{% else %}neuvedeno{% endif %}</td>
    </tr>
    <tr>
      <th style="text-align: left;padding: 4px">DIČ:</th>
      <td>{% if dic %}{{ dic }}{% else %}neuvedeno{% endif %}</td>
    </tr>
</table>
<h3>Objednávka:</h3>
<hr>
{% if order.orderproduct_set.count == 0 %}
<b>Objednavatel nezadal žádné produkty.</b>
{% else %}
<table style="border: 1px solid #e8e8e8;padding: 6px;width: 100%;border-collapse: collapse;">
    <tr>
        <th style="text-align: left;padding: 8px;border-bottom: 1px solid #ececec;">Produkt</th>
        <th style="text-align: left;padding: 8px;border-bottom: 1px solid #ececec;">Množství</th>
    </tr>
{% for product in order.orderproduct_set.all %}
    <tr style="background-color: {% cycle '#ffffff' '#f9f9f9' %}">
      <td style="text-align: left;padding: 8px">{{ product.get_type_of_product_display }}</td>
      <td style="text-align: left;padding: 8px">{{ product.quantity }}</td>
    </tr>
{% endfor %}
</table>
{% endif %}

leonardo_kkadavy_orders/templates/leonardo_kkadavy_orders/kkadavyorders_form.html
{% extends "leonardo/common/modal.html" %}
{% load i18n staticfiles %}

{% block title %}{% trans "Order" %}{% endblock %}

{% block page_header %}
{% include "horizon/common/_page_header.html" with title=_("Order") %}
{% endblock %}

{% block body_main %}
{% include "leonardo_kkadavy_orders/_kkadavyorders_form.html" %}
{% endblock %}